before:
  hooks:
    - go mod download

builds:
-
  env:
    - CGO_ENABLED=1

  goos:
    - linux

  goarch:
    - amd64

archive:
  format: binary

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc

  filters:
    exclude:
    - '^Document'
    - typo
